In [60]:
import numpy as np
from sklearn.decomposition import NMF

In [61]:
Y = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])

In [62]:
# Use scikit learn NMR

In [63]:
model = NMF(n_components=2, init='random', random_state=0)
A = model.fit_transform(Y)
X = model.components_

In [64]:
np.shape(Y),np.shape(A),np.shape(X)

((6, 2), (6, 2), (2, 2))

In [65]:
Y-np.dot(A,X)

array([[-6.35579822e-04,  6.36528773e-04],
       [ 3.40231372e-04, -3.40739354e-04],
       [ 3.45147253e-04, -3.45662574e-04],
       [ 1.31898319e-04, -1.32095249e-04],
       [-9.00218123e-05,  9.01562192e-05],
       [-8.58722020e-05,  8.60004133e-05]])

In [ ]:
# Lee and Seung -- multiplicative iterative method

In [78]:
ddim=2
A0=np.random.rand(np.shape(Y)[0],ddim)
X0=np.random.rand(ddim,np.shape(Y)[1])

In [79]:
A=np.copy(A0)
X=np.copy(X0)
epsilon=1.e-6
for i in range(0,1000):
    Wt = np.dot(Y,X.T)
    Wb = np.dot(np.dot(A,X),X.T) + epsilon
    #print(np.shape(Wt/Wb),np.shape(A))
    A = A*(Wt/Wb)

    Wt = np.dot(A.T,Y)
    Wb = np.dot(np.dot(A.T,A),X) + epsilon 
    X = X*(Wt/Wb)

In [80]:
    print(np.sum(Y-np.dot(A,X)))

1.8918906343756703e-06


In [81]:
A

array([[1.39282109e+00, 1.27900056e-08],
       [1.39152262e+00, 9.85588935e-01],
       [1.66904777e+00, 1.77406075e+00],
       [1.38892434e+00, 2.95676866e+00],
       [1.10880091e+00, 4.13947657e+00],
       [1.38632607e+00, 4.92794839e+00]])

In [82]:
X

array([[7.17967074e-01, 7.17966864e-01],
       [1.01556741e+00, 9.46412616e-04]])