In [1]:
import gpmatrix 
import numpy as np
from sklearn.datasets import make_spd_matrix
import scipy

In [229]:
Ni=3
Nj=5
W=np.random.random((Ni,Nj))
tilW=gpmatrix.make_tilW(W)

In [230]:
W

array([[0.92249796, 0.34143647, 0.86567877, 0.414497  , 0.35078144],
       [0.29904709, 0.87380592, 0.41278311, 0.16658541, 0.59967902],
       [0.98774947, 0.65428259, 0.24682309, 0.40086325, 0.33485015]])

In [231]:
def vec(A):
    return A.T.reshape(Ni*Nj)

In [232]:
vec(W)

array([0.92249796, 0.29904709, 0.98774947, 0.34143647, 0.87380592,
       0.65428259, 0.86567877, 0.41278311, 0.24682309, 0.414497  ,
       0.16658541, 0.40086325, 0.35078144, 0.59967902, 0.33485015])

In [233]:
def mat(A):
    return (A.reshape(Nj,Ni)).T

In [234]:
W-mat(vec(W))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [235]:
A=np.random.random((Ni,Nj))

## basic expansion/contraction relation

In [236]:
tilW@vec(A)-np.sum(W*A,axis=1)

array([0., 0., 0.])

## Recontraction Formula 1

In [237]:
S=make_spd_matrix(Nj)
T=make_spd_matrix(Ni)

In [238]:
Y1=tilW@(np.kron(S,T))@tilW.T

In [239]:
Y2=T*(W@S@W.T)

In [240]:
Y1-Y2

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16, -8.88178420e-16, -4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00, -1.77635684e-15]])

## Recontraction Formula 2

In [241]:
X=np.random.random(Ni)

In [242]:
Y1=mat(np.kron(S,T)@tilW.T@X)

In [244]:
Wx=W*(np.outer(X,np.ones(Nj)))
Y2=T@Wx@S

In [245]:
Y1-Y2

array([[ 8.88178420e-16,  1.11022302e-15,  4.16333634e-16,
        -1.08940634e-15, -1.37043155e-16],
       [-5.55111512e-15,  8.88178420e-16, -1.33226763e-15,
         3.33066907e-15,  1.60982339e-15],
       [-7.54951657e-15,  3.55271368e-15, -1.33226763e-15,
         3.99680289e-15,  2.72004641e-15]])

In [246]:
Y3=(T*X)@W@S

In [247]:
Y1-Y3

array([[ 8.88178420e-16,  1.16573418e-15,  4.71844785e-16,
        -1.08940634e-15, -1.45716772e-16],
       [-5.77315973e-15,  4.44089210e-16, -1.33226763e-15,
         3.77475828e-15,  1.60982339e-15],
       [-7.54951657e-15,  3.55271368e-15, -1.33226763e-15,
         3.99680289e-15,  2.77555756e-15]])

In [253]:
Y4=T@(W.T*X).T@S

In [254]:
Y1-Y4

array([[ 8.88178420e-16,  1.11022302e-15,  4.16333634e-16,
        -1.08940634e-15, -1.37043155e-16],
       [-5.55111512e-15,  8.88178420e-16, -1.33226763e-15,
         3.33066907e-15,  1.60982339e-15],
       [-7.54951657e-15,  3.55271368e-15, -1.33226763e-15,
         3.99680289e-15,  2.72004641e-15]])

In [251]:
Y5=T@(X*W.T).T@S

In [252]:
Y1-Y5

array([[ 8.88178420e-16,  1.11022302e-15,  4.16333634e-16,
        -1.08940634e-15, -1.37043155e-16],
       [-5.55111512e-15,  8.88178420e-16, -1.33226763e-15,
         3.33066907e-15,  1.60982339e-15],
       [-7.54951657e-15,  3.55271368e-15, -1.33226763e-15,
         3.99680289e-15,  2.72004641e-15]])

### speed check

In [220]:
Ni=100
Nj=150
W=np.random.random((Ni,Nj))
tilW=gpmatrix.make_tilW(W)
S=make_spd_matrix(Nj)
T=make_spd_matrix(Ni)
X=np.random.random(Ni)

In [226]:
import time 
#ts = time.time()
#Y1=mat(np.kron(S,T)@tilW.T@X)
#te = time.time()
#print("Y1",te-ts)

ts = time.time()
Wx=W*(np.outer(X,np.ones(Nj)))
Y2=T@Wx@S
te = time.time()
print("Y2",te-ts)

ts = time.time()
Wx=W*(np.outer(X,np.ones(Nj)))
Y3=(T*X)@W@S
te = time.time()
print("Y3",te-ts)

ts = time.time()
Y4=T@(W.T*X).T@S
te = time.time()
print("Y4",te-ts)

ts = time.time()
Y5=T@(X*W.T).T@S
te = time.time()
print("Y5",te-ts)



#print(np.sum((Y1-Y2)**2),np.sum((Y1-Y3)**2),np.sum((Y1-Y4)**2),np.sum((Y1-Y5)**2))

Y2 0.0008399486541748047
Y3 0.0005054473876953125
Y4 0.0003819465637207031
Y5 0.00046181678771972656
